command_timeout = 1000
format = """
$username\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$git_metrics\
$nodejs\
$golang\
$bun\
$fill\
$cmd_duration\
$time\
$line_break
$character
"""

add_newline = false

# backup character
# connections:  ╭─
# 󰂵           󰝨 󰙴  󰊠 󱙝 
# directory:     󰷏
# omit: ⚛︎ · 󱏿·     󰝡 …
# git thing:   
#

palette = "mypalette"

[palettes.mypalette]
blue = "#3a9efd"
orange = "#fca17d"
red = "#eb3b5a"
cyan = "#1ac0c6"
text_color = "#ffffff"
background = "#3b3f4c"
transient_prompt = "#3a9efd"
username_color = "#3a9efd"
directory_color = "#DA627D"
git_color = "#fca17d"
cmd_duration = "#ffffff"
time_color = "#1ac0c6"
node_color = "#6a994e"
go_color = "#00ADD8"
bun_color = "#a277ff"


[env_var.transient_prompt]
default="transient_prompt"
style = "transient_prompt"
format = "\n[](fg:$style)[ 󰊠 ](bold fg:text_color bg:$style)[](fg:$style)[  ](fg:#FCA17D)"

[username]
show_always = true
style_user = "username_color"
style_root = "username_color"
format = """
[](fg:$style)[  ](bold fg:text_color bg:$style)[](fg:$style)\
[](fg:background)[$user](bold fg:$style bg:background)[ ](fg:background)\
"""

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "directory_color"
format = """
[](fg:$style)[](bold fg:text_color bg:$style)[](fg:$style)\
[](fg:background)[$path](bold fg:$style bg:background)[ ](fg:background)\
"""

[directory.substitutions]
"documents" = "󰲂"
"downloads" = ""
"music" = ""
"pictures" = ""

[git_branch]
symbol = ""
style = "git_color"
format = """
[](fg:$style)[](bold fg:text_color bg:$style)[](fg:$style)\
[](background)[$symbol $branch](bold fg:$style bg:background)\
"""

[git_status]
style = "git_color"
modified = "󰙏 "
deleted = " "
untracked = "󰐕 "
staged = " "
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = """
[ $all_status](fg:$style bg:background)[ ](fg:background)\
"""

[nodejs]
symbol = ""
style = "node_color"
format = """
[](fg:$style)[$symbol](bold fg:text_color bg:$style)[](fg:$style)\
[](fg:background)[$version](bold fg:$style bg:background)[ ](fg:background)\
"""

[golang]
symbol = ""
style = "go_color"
version_format = "v$major.$minor"
format = """
[](fg:$style)[$symbol](bold fg:text_color bg:$style)[](fg:$style)\
[](fg:background)[$version](bold fg:$style bg:background)[ ](fg:background)\
"""

[bun]
symbol = ""
style = "bun_color"
version_format = "v$major.$minor.$patch"
format = """
[](fg:$style)[$symbol](bold fg:text_color bg:$style)[](fg:$style)\
[](fg:background)[$version](bold fg:$style bg:background)[ ](fg:background)\
"""


[fill]
# symbol = "  ✎     ⚛︎                       "
symbol = " "
style = "cyan bold"

[cmd_duration]
# min_time = 0
style = "cmd_duration"
format = "[took ](fg:$style)[$duration  ](bold fg:orange)"
# [](fg:orange)[took ](bold fg:$style bg:orange)[ $duration](bold fg:orange bg:white)[](fg:white)\

[time]
disabled = false
time_format = "%R"
style = "time_color"
format = """
[](fg:background)[ $time ](bold fg:$style bg:background)[](fg:background)\
[](fg:$style bg:background)[](bold fg:text_color bg:$style)[ ](fg:$style)\
"""

[character]
success_symbol = '[](fg:#FCA17D)' #╰─  󱞩   󰁔 󱦰 󱞪   👉
error_symbol = '[](fg:#eb3b5a)' # 💤💥💣💬😅
vimcmd_symbol = '[](fg:#1ac0c6)'

[line_break]
disabled = true
